---
- name: Ensure MySQL databases are present.
  mysql_db:
    name: "{{ item.name }}"
    login_user:     "{{ login_user }}"
    login_host:     "{{ login_host }}"
    login_password: "{{ login_password }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    state: present
  with_items: "{{ mysql_databases }}"
